DEBUG = -ansi -pedantic-errors -Wall -Wextra -g
CC = gcc


server:
	cc $(DEBUG) server.c -o server

tcp_client:
	cc  $(DEBUG) tcp_client.c -o tcp_client 

udp_client:
	cc  $(DEBUG) udp_client.c -o udp_client
	

